### ISSUE TITLE
Some html tags disappear after setHTML.

### ISSUE THREAD

**Issue by evpozdniakov** [froala/wysiwyg-editor-v1#24]
We noticed that if you left the editor open for a few minutes, then method editable('setHML') starts modifying your original html, like removing some tags or style attributes.
E.g. ```<p><u>test</u></p>``` will become ```<p>test</p>```

Is it a know issue?

**Comment by evpozdniakov** [comment]
Actually, we use single instance for editing multiple texts. So we call ```editable('setHML', str)``` to switch between texts.

**Comment by evpozdniakov** [comment]
The version we use is 1.2.7

**Comment by stefanneculai** [comment]
We're no longer maintaining version 1. Please upgrade to V2.
